// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication_MVC_GRUPO8.Context;

#nullable disable

namespace WebApplication_MVC_GRUPO8.Migrations
{
    [DbContext(typeof(SistemaMantenimientoDBContext))]
    [Migration("20251122143633_cambiosComentarioIncidencia2")]
    partial class cambiosComentarioIncidencia2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication_MVC_GRUPO8.Models.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("categoriaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("WebApplication_MVC_GRUPO8.Models.Comentario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("fechaComentario")
                        .HasColumnType("datetime2");

                    b.Property<int>("idIncidencia")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idIncidencia");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("WebApplication_MVC_GRUPO8.Models.Incidencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("complejidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("costoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcionGasto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estadoIncidencia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaFinReparacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaInicioReparacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("idEncargado")
                        .HasColumnType("int");

                    b.Property<int?>("idTecnico")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("imagenFinalIncidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagenIncidencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("justificacionDescarte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("prioridad")
                        .HasColumnType("int");

                    b.Property<decimal?>("sla")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idCategoria");

                    b.HasIndex("idEncargado");

                    b.HasIndex("idTecnico");

                    b.HasIndex("idUsuario");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("WebApplication_MVC_GRUPO8.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rol")
                        .HasColumnType("int");

                    b.Property<bool>("userActivo")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApplication_MVC_GRUPO8.Models.Comentario", b =>
                {
                    b.HasOne("WebApplication_MVC_GRUPO8.Models.Incidencia", "Incidencia")
                        .WithMany("Comentarios")
                        .HasForeignKey("idIncidencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidencia");
                });

            modelBuilder.Entity("WebApplication_MVC_GRUPO8.Models.Incidencia", b =>
                {
                    b.HasOne("WebApplication_MVC_GRUPO8.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication_MVC_GRUPO8.Models.User", "Encargado")
                        .WithMany()
                        .HasForeignKey("idEncargado");

                    b.HasOne("WebApplication_MVC_GRUPO8.Models.User", "Tecnico")
                        .WithMany()
                        .HasForeignKey("idTecnico");

                    b.HasOne("WebApplication_MVC_GRUPO8.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Encargado");

                    b.Navigation("Tecnico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplication_MVC_GRUPO8.Models.Incidencia", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
